/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ECFDLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class FileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.File");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cListEcfdKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cEcfdAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cEcfdEcfdParserRuleCall_2_0 = (RuleCall)cEcfdAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cEcfdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cEcfdEcfdParserRuleCall_3_1_0 = (RuleCall)cEcfdAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//File:
		//	'listEcfd' '{' ecfd+=Ecfd ("," ecfd+=Ecfd)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'listEcfd' '{' ecfd+=Ecfd ("," ecfd+=Ecfd)* '}'
		public Group getGroup() { return cGroup; }
		
		//'listEcfd'
		public Keyword getListEcfdKeyword_0() { return cListEcfdKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//ecfd+=Ecfd
		public Assignment getEcfdAssignment_2() { return cEcfdAssignment_2; }
		
		//Ecfd
		public RuleCall getEcfdEcfdParserRuleCall_2_0() { return cEcfdEcfdParserRuleCall_2_0; }
		
		//("," ecfd+=Ecfd)*
		public Group getGroup_3() { return cGroup_3; }
		
		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//ecfd+=Ecfd
		public Assignment getEcfdAssignment_3_1() { return cEcfdAssignment_3_1; }
		
		//Ecfd
		public RuleCall getEcfdEcfdParserRuleCall_3_1_0() { return cEcfdEcfdParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EcfdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.Ecfd");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEcfdAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEcfdKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cBoxesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cBoxesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cBoxesBoxParserRuleCall_5_2_0 = (RuleCall)cBoxesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cBoxesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cBoxesBoxParserRuleCall_5_3_1_0 = (RuleCall)cBoxesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cGroupsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cGroupsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cGroupsGroupBoxParserRuleCall_6_2_0 = (RuleCall)cGroupsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cBoxesAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cBoxesGroupBoxParserRuleCall_6_3_1_0 = (RuleCall)cBoxesAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMutexKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Assignment cMutexAssignment_7_2_0 = (Assignment)cGroup_7_2.eContents().get(0);
		private final RuleCall cMutexMutexParserRuleCall_7_2_0_0 = (RuleCall)cMutexAssignment_7_2_0.eContents().get(0);
		private final Group cGroup_7_2_1 = (Group)cGroup_7_2.eContents().get(1);
		private final Keyword cCommaKeyword_7_2_1_0 = (Keyword)cGroup_7_2_1.eContents().get(0);
		private final Assignment cMutexAssignment_7_2_1_1 = (Assignment)cGroup_7_2_1.eContents().get(1);
		private final RuleCall cMutexMutexParserRuleCall_7_2_1_1_0 = (RuleCall)cMutexAssignment_7_2_1_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Ecfd:
		//	{Ecfd}
		//	'Ecfd' ':' name=ID
		//	'{' ('boxes' '{' boxes+=Box ("," boxes+=Box)* '}') ('groups' '{' groups+=GroupBox ("," boxes+=GroupBox)* '}')?
		//	('mutex' '{' (mutex+=Mutex ("," mutex+=Mutex)*)? '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Ecfd} 'Ecfd' ':' name=ID '{' ('boxes' '{' boxes+=Box ("," boxes+=Box)* '}') ('groups' '{' groups+=GroupBox (","
		//boxes+=GroupBox)* '}')? ('mutex' '{' (mutex+=Mutex ("," mutex+=Mutex)*)? '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Ecfd}
		public Action getEcfdAction_0() { return cEcfdAction_0; }
		
		//'Ecfd'
		public Keyword getEcfdKeyword_1() { return cEcfdKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//('boxes' '{' boxes+=Box ("," boxes+=Box)* '}')
		public Group getGroup_5() { return cGroup_5; }
		
		//'boxes'
		public Keyword getBoxesKeyword_5_0() { return cBoxesKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//boxes+=Box
		public Assignment getBoxesAssignment_5_2() { return cBoxesAssignment_5_2; }
		
		//Box
		public RuleCall getBoxesBoxParserRuleCall_5_2_0() { return cBoxesBoxParserRuleCall_5_2_0; }
		
		//("," boxes+=Box)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//boxes+=Box
		public Assignment getBoxesAssignment_5_3_1() { return cBoxesAssignment_5_3_1; }
		
		//Box
		public RuleCall getBoxesBoxParserRuleCall_5_3_1_0() { return cBoxesBoxParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('groups' '{' groups+=GroupBox ("," boxes+=GroupBox)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'groups'
		public Keyword getGroupsKeyword_6_0() { return cGroupsKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//groups+=GroupBox
		public Assignment getGroupsAssignment_6_2() { return cGroupsAssignment_6_2; }
		
		//GroupBox
		public RuleCall getGroupsGroupBoxParserRuleCall_6_2_0() { return cGroupsGroupBoxParserRuleCall_6_2_0; }
		
		//("," boxes+=GroupBox)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//boxes+=GroupBox
		public Assignment getBoxesAssignment_6_3_1() { return cBoxesAssignment_6_3_1; }
		
		//GroupBox
		public RuleCall getBoxesGroupBoxParserRuleCall_6_3_1_0() { return cBoxesGroupBoxParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('mutex' '{' (mutex+=Mutex ("," mutex+=Mutex)*)? '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'mutex'
		public Keyword getMutexKeyword_7_0() { return cMutexKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//(mutex+=Mutex ("," mutex+=Mutex)*)?
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//mutex+=Mutex
		public Assignment getMutexAssignment_7_2_0() { return cMutexAssignment_7_2_0; }
		
		//Mutex
		public RuleCall getMutexMutexParserRuleCall_7_2_0_0() { return cMutexMutexParserRuleCall_7_2_0_0; }
		
		//("," mutex+=Mutex)*
		public Group getGroup_7_2_1() { return cGroup_7_2_1; }
		
		//","
		public Keyword getCommaKeyword_7_2_1_0() { return cCommaKeyword_7_2_1_0; }
		
		//mutex+=Mutex
		public Assignment getMutexAssignment_7_2_1_1() { return cMutexAssignment_7_2_1_1; }
		
		//Mutex
		public RuleCall getMutexMutexParserRuleCall_7_2_1_1_0() { return cMutexMutexParserRuleCall_7_2_1_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBoxParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGroupBoxParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Element:
		//	Box | GroupBox;
		@Override public ParserRule getRule() { return rule; }
		
		//Box | GroupBox
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Box
		public RuleCall getBoxParserRuleCall_0() { return cBoxParserRuleCall_0; }
		
		//GroupBox
		public RuleCall getGroupBoxParserRuleCall_1() { return cGroupBoxParserRuleCall_1; }
	}
	public class MutexElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.Mutex");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMutexKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cBoxesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cBoxAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cBoxBoxCrossReference_6_0 = (CrossReference)cBoxAssignment_6.eContents().get(0);
		private final RuleCall cBoxBoxIDTerminalRuleCall_6_0_1 = (RuleCall)cBoxBoxCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cBoxAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cBoxBoxCrossReference_7_1_0 = (CrossReference)cBoxAssignment_7_1.eContents().get(0);
		private final RuleCall cBoxBoxIDTerminalRuleCall_7_1_0_1 = (RuleCall)cBoxBoxCrossReference_7_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Mutex:
		//	'Mutex' ':' name=ID
		//	'{'
		//	'boxes' '(' box+=[Box] ("," box+=[Box])+ ')' // modification de '*' pour un '+'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Mutex' ':' name=ID '{' 'boxes' '(' box+=[Box] ("," box+=[Box])+ ')' // modification de '*' pour un '+'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Mutex'
		public Keyword getMutexKeyword_0() { return cMutexKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//'boxes'
		public Keyword getBoxesKeyword_4() { return cBoxesKeyword_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5() { return cLeftParenthesisKeyword_5; }
		
		//box+=[Box]
		public Assignment getBoxAssignment_6() { return cBoxAssignment_6; }
		
		//[Box]
		public CrossReference getBoxBoxCrossReference_6_0() { return cBoxBoxCrossReference_6_0; }
		
		//ID
		public RuleCall getBoxBoxIDTerminalRuleCall_6_0_1() { return cBoxBoxIDTerminalRuleCall_6_0_1; }
		
		//("," box+=[Box])+
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//box+=[Box]
		public Assignment getBoxAssignment_7_1() { return cBoxAssignment_7_1; }
		
		//[Box]
		public CrossReference getBoxBoxCrossReference_7_1_0() { return cBoxBoxCrossReference_7_1_0; }
		
		//ID
		public RuleCall getBoxBoxIDTerminalRuleCall_7_1_0_1() { return cBoxBoxIDTerminalRuleCall_7_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//// modification de '*' pour un '+'
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class BoxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.Box");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBoxAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBoxKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRootAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cRootRootKeyword_5_0 = (Keyword)cRootAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cSuperBoxKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cSuperBoxAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cSuperBoxBoxCrossReference_6_2_0 = (CrossReference)cSuperBoxAssignment_6_2.eContents().get(0);
		private final RuleCall cSuperBoxBoxIDTerminalRuleCall_6_2_0_1 = (RuleCall)cSuperBoxBoxCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cSuperBoxAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cSuperBoxBoxCrossReference_6_3_1_0 = (CrossReference)cSuperBoxAssignment_6_3_1.eContents().get(0);
		private final RuleCall cSuperBoxBoxIDTerminalRuleCall_6_3_1_0_1 = (RuleCall)cSuperBoxBoxCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cGroupboxKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cGroupboxAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final CrossReference cGroupboxGroupBoxCrossReference_7_2_0 = (CrossReference)cGroupboxAssignment_7_2.eContents().get(0);
		private final RuleCall cGroupboxGroupBoxIDTerminalRuleCall_7_2_0_1 = (RuleCall)cGroupboxGroupBoxCrossReference_7_2_0.eContents().get(1);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cGroupboxAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final CrossReference cGroupboxGroupBoxCrossReference_7_3_1_0 = (CrossReference)cGroupboxAssignment_7_3_1.eContents().get(0);
		private final RuleCall cGroupboxGroupBoxIDTerminalRuleCall_7_3_1_0_1 = (RuleCall)cGroupboxGroupBoxCrossReference_7_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cMotherOfKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cChildBoxAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final CrossReference cChildBoxBoxCrossReference_8_2_0 = (CrossReference)cChildBoxAssignment_8_2.eContents().get(0);
		private final RuleCall cChildBoxBoxIDTerminalRuleCall_8_2_0_1 = (RuleCall)cChildBoxBoxCrossReference_8_2_0.eContents().get(1);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cChildBoxAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final CrossReference cChildBoxBoxCrossReference_8_3_1_0 = (CrossReference)cChildBoxAssignment_8_3_1.eContents().get(0);
		private final RuleCall cChildBoxBoxIDTerminalRuleCall_8_3_1_0_1 = (RuleCall)cChildBoxBoxCrossReference_8_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cMotherOfGroupKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cChildGroupAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final CrossReference cChildGroupGroupBoxCrossReference_9_2_0 = (CrossReference)cChildGroupAssignment_9_2.eContents().get(0);
		private final RuleCall cChildGroupGroupBoxIDTerminalRuleCall_9_2_0_1 = (RuleCall)cChildGroupGroupBoxCrossReference_9_2_0.eContents().get(1);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cChildGroupAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final CrossReference cChildGroupGroupBoxCrossReference_9_3_1_0 = (CrossReference)cChildGroupAssignment_9_3_1.eContents().get(0);
		private final RuleCall cChildGroupGroupBoxIDTerminalRuleCall_9_3_1_0_1 = (RuleCall)cChildGroupGroupBoxCrossReference_9_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cMutexKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cMutexAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final CrossReference cMutexMutexCrossReference_10_2_0 = (CrossReference)cMutexAssignment_10_2.eContents().get(0);
		private final RuleCall cMutexMutexIDTerminalRuleCall_10_2_0_1 = (RuleCall)cMutexMutexCrossReference_10_2_0.eContents().get(1);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cMutexAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final CrossReference cMutexMutexCrossReference_10_3_1_0 = (CrossReference)cMutexAssignment_10_3_1.eContents().get(0);
		private final RuleCall cMutexMutexIDTerminalRuleCall_10_3_1_0_1 = (RuleCall)cMutexMutexCrossReference_10_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cFeaturesKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cFeatureAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cFeatureFeatureParserRuleCall_11_2_0 = (RuleCall)cFeatureAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cFeatureAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cFeatureFeatureParserRuleCall_11_3_1_0 = (RuleCall)cFeatureAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Box:
		//	{Box}
		//	'Box' ':' name=ID
		//	'{'
		//	Root?='Root'? ('superBox' '(' superBox+=[Box] ("," superBox+=[Box])* ')')? ('groupbox' '(' groupbox+=[GroupBox] (","
		//	groupbox+=[GroupBox])* ')')? ('motherOf' '(' childBox+=[Box] ("," childBox+=[Box])* ')')? ('motherOfGroup' '('
		//	childGroup+=[GroupBox] ("," childGroup+=[GroupBox])* ')')? ('mutex' '(' mutex+=[Mutex] ("," mutex+=[Mutex])* ')')?
		//	('features' '(' feature+=Feature ("," feature+=Feature)* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Box} 'Box' ':' name=ID '{' Root?='Root'? ('superBox' '(' superBox+=[Box] ("," superBox+=[Box])* ')')? ('groupbox' '('
		//groupbox+=[GroupBox] ("," groupbox+=[GroupBox])* ')')? ('motherOf' '(' childBox+=[Box] ("," childBox+=[Box])* ')')?
		//('motherOfGroup' '(' childGroup+=[GroupBox] ("," childGroup+=[GroupBox])* ')')? ('mutex' '(' mutex+=[Mutex] (","
		//mutex+=[Mutex])* ')')? ('features' '(' feature+=Feature ("," feature+=Feature)* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Box}
		public Action getBoxAction_0() { return cBoxAction_0; }
		
		//'Box'
		public Keyword getBoxKeyword_1() { return cBoxKeyword_1; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//Root?='Root'?
		public Assignment getRootAssignment_5() { return cRootAssignment_5; }
		
		//'Root'
		public Keyword getRootRootKeyword_5_0() { return cRootRootKeyword_5_0; }
		
		//('superBox' '(' superBox+=[Box] ("," superBox+=[Box])* ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'superBox'
		public Keyword getSuperBoxKeyword_6_0() { return cSuperBoxKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//superBox+=[Box]
		public Assignment getSuperBoxAssignment_6_2() { return cSuperBoxAssignment_6_2; }
		
		//[Box]
		public CrossReference getSuperBoxBoxCrossReference_6_2_0() { return cSuperBoxBoxCrossReference_6_2_0; }
		
		//ID
		public RuleCall getSuperBoxBoxIDTerminalRuleCall_6_2_0_1() { return cSuperBoxBoxIDTerminalRuleCall_6_2_0_1; }
		
		//("," superBox+=[Box])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//superBox+=[Box]
		public Assignment getSuperBoxAssignment_6_3_1() { return cSuperBoxAssignment_6_3_1; }
		
		//[Box]
		public CrossReference getSuperBoxBoxCrossReference_6_3_1_0() { return cSuperBoxBoxCrossReference_6_3_1_0; }
		
		//ID
		public RuleCall getSuperBoxBoxIDTerminalRuleCall_6_3_1_0_1() { return cSuperBoxBoxIDTerminalRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('groupbox' '(' groupbox+=[GroupBox] ("," groupbox+=[GroupBox])* ')')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'groupbox'
		public Keyword getGroupboxKeyword_7_0() { return cGroupboxKeyword_7_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_7_1() { return cLeftParenthesisKeyword_7_1; }
		
		//groupbox+=[GroupBox]
		public Assignment getGroupboxAssignment_7_2() { return cGroupboxAssignment_7_2; }
		
		//[GroupBox]
		public CrossReference getGroupboxGroupBoxCrossReference_7_2_0() { return cGroupboxGroupBoxCrossReference_7_2_0; }
		
		//ID
		public RuleCall getGroupboxGroupBoxIDTerminalRuleCall_7_2_0_1() { return cGroupboxGroupBoxIDTerminalRuleCall_7_2_0_1; }
		
		//("," groupbox+=[GroupBox])*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//groupbox+=[GroupBox]
		public Assignment getGroupboxAssignment_7_3_1() { return cGroupboxAssignment_7_3_1; }
		
		//[GroupBox]
		public CrossReference getGroupboxGroupBoxCrossReference_7_3_1_0() { return cGroupboxGroupBoxCrossReference_7_3_1_0; }
		
		//ID
		public RuleCall getGroupboxGroupBoxIDTerminalRuleCall_7_3_1_0_1() { return cGroupboxGroupBoxIDTerminalRuleCall_7_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_4() { return cRightParenthesisKeyword_7_4; }
		
		//('motherOf' '(' childBox+=[Box] ("," childBox+=[Box])* ')')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'motherOf'
		public Keyword getMotherOfKeyword_8_0() { return cMotherOfKeyword_8_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_8_1() { return cLeftParenthesisKeyword_8_1; }
		
		//childBox+=[Box]
		public Assignment getChildBoxAssignment_8_2() { return cChildBoxAssignment_8_2; }
		
		//[Box]
		public CrossReference getChildBoxBoxCrossReference_8_2_0() { return cChildBoxBoxCrossReference_8_2_0; }
		
		//ID
		public RuleCall getChildBoxBoxIDTerminalRuleCall_8_2_0_1() { return cChildBoxBoxIDTerminalRuleCall_8_2_0_1; }
		
		//("," childBox+=[Box])*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//childBox+=[Box]
		public Assignment getChildBoxAssignment_8_3_1() { return cChildBoxAssignment_8_3_1; }
		
		//[Box]
		public CrossReference getChildBoxBoxCrossReference_8_3_1_0() { return cChildBoxBoxCrossReference_8_3_1_0; }
		
		//ID
		public RuleCall getChildBoxBoxIDTerminalRuleCall_8_3_1_0_1() { return cChildBoxBoxIDTerminalRuleCall_8_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8_4() { return cRightParenthesisKeyword_8_4; }
		
		//('motherOfGroup' '(' childGroup+=[GroupBox] ("," childGroup+=[GroupBox])* ')')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'motherOfGroup'
		public Keyword getMotherOfGroupKeyword_9_0() { return cMotherOfGroupKeyword_9_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_9_1() { return cLeftParenthesisKeyword_9_1; }
		
		//childGroup+=[GroupBox]
		public Assignment getChildGroupAssignment_9_2() { return cChildGroupAssignment_9_2; }
		
		//[GroupBox]
		public CrossReference getChildGroupGroupBoxCrossReference_9_2_0() { return cChildGroupGroupBoxCrossReference_9_2_0; }
		
		//ID
		public RuleCall getChildGroupGroupBoxIDTerminalRuleCall_9_2_0_1() { return cChildGroupGroupBoxIDTerminalRuleCall_9_2_0_1; }
		
		//("," childGroup+=[GroupBox])*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//childGroup+=[GroupBox]
		public Assignment getChildGroupAssignment_9_3_1() { return cChildGroupAssignment_9_3_1; }
		
		//[GroupBox]
		public CrossReference getChildGroupGroupBoxCrossReference_9_3_1_0() { return cChildGroupGroupBoxCrossReference_9_3_1_0; }
		
		//ID
		public RuleCall getChildGroupGroupBoxIDTerminalRuleCall_9_3_1_0_1() { return cChildGroupGroupBoxIDTerminalRuleCall_9_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9_4() { return cRightParenthesisKeyword_9_4; }
		
		//('mutex' '(' mutex+=[Mutex] ("," mutex+=[Mutex])* ')')?
		public Group getGroup_10() { return cGroup_10; }
		
		//'mutex'
		public Keyword getMutexKeyword_10_0() { return cMutexKeyword_10_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_10_1() { return cLeftParenthesisKeyword_10_1; }
		
		//mutex+=[Mutex]
		public Assignment getMutexAssignment_10_2() { return cMutexAssignment_10_2; }
		
		//[Mutex]
		public CrossReference getMutexMutexCrossReference_10_2_0() { return cMutexMutexCrossReference_10_2_0; }
		
		//ID
		public RuleCall getMutexMutexIDTerminalRuleCall_10_2_0_1() { return cMutexMutexIDTerminalRuleCall_10_2_0_1; }
		
		//("," mutex+=[Mutex])*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//mutex+=[Mutex]
		public Assignment getMutexAssignment_10_3_1() { return cMutexAssignment_10_3_1; }
		
		//[Mutex]
		public CrossReference getMutexMutexCrossReference_10_3_1_0() { return cMutexMutexCrossReference_10_3_1_0; }
		
		//ID
		public RuleCall getMutexMutexIDTerminalRuleCall_10_3_1_0_1() { return cMutexMutexIDTerminalRuleCall_10_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_10_4() { return cRightParenthesisKeyword_10_4; }
		
		//('features' '(' feature+=Feature ("," feature+=Feature)* ')')?
		public Group getGroup_11() { return cGroup_11; }
		
		//'features'
		public Keyword getFeaturesKeyword_11_0() { return cFeaturesKeyword_11_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_11_1() { return cLeftParenthesisKeyword_11_1; }
		
		//feature+=Feature
		public Assignment getFeatureAssignment_11_2() { return cFeatureAssignment_11_2; }
		
		//Feature
		public RuleCall getFeatureFeatureParserRuleCall_11_2_0() { return cFeatureFeatureParserRuleCall_11_2_0; }
		
		//("," feature+=Feature)*
		public Group getGroup_11_3() { return cGroup_11_3; }
		
		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }
		
		//feature+=Feature
		public Assignment getFeatureAssignment_11_3_1() { return cFeatureAssignment_11_3_1; }
		
		//Feature
		public RuleCall getFeatureFeatureParserRuleCall_11_3_1_0() { return cFeatureFeatureParserRuleCall_11_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_11_4() { return cRightParenthesisKeyword_11_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class GroupBoxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.GroupBox");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupBoxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExclusifAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cExclusifExclusifKeyword_4_0 = (Keyword)cExclusifAssignment_4.eContents().get(0);
		private final Keyword cSuperBoxKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSuperBoxAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cSuperBoxBoxCrossReference_7_0 = (CrossReference)cSuperBoxAssignment_7.eContents().get(0);
		private final RuleCall cSuperBoxBoxIDTerminalRuleCall_7_0_1 = (RuleCall)cSuperBoxBoxCrossReference_7_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cBoxesKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cBoxAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cBoxBoxCrossReference_11_0 = (CrossReference)cBoxAssignment_11.eContents().get(0);
		private final RuleCall cBoxBoxIDTerminalRuleCall_11_0_1 = (RuleCall)cBoxBoxCrossReference_11_0.eContents().get(1);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cCommaKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cBoxAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cBoxBoxCrossReference_12_1_0 = (CrossReference)cBoxAssignment_12_1.eContents().get(0);
		private final RuleCall cBoxBoxIDTerminalRuleCall_12_1_0_1 = (RuleCall)cBoxBoxCrossReference_12_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//GroupBox:
		//	'GroupBox' ':' name=ID
		//	'{'
		//	Exclusif?='Exclusif'?
		//	'superBox' '(' superBox+=[Box] ')'
		//	'boxes' '(' box+=[Box] ("," box+=[Box])+ ')' // modification de '*' pour un '+'
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GroupBox' ':' name=ID '{' Exclusif?='Exclusif'? 'superBox' '(' superBox+=[Box] ')' 'boxes' '(' box+=[Box] (","
		//box+=[Box])+ ')' // modification de '*' pour un '+'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'GroupBox'
		public Keyword getGroupBoxKeyword_0() { return cGroupBoxKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//Exclusif?='Exclusif'?
		public Assignment getExclusifAssignment_4() { return cExclusifAssignment_4; }
		
		//'Exclusif'
		public Keyword getExclusifExclusifKeyword_4_0() { return cExclusifExclusifKeyword_4_0; }
		
		//'superBox'
		public Keyword getSuperBoxKeyword_5() { return cSuperBoxKeyword_5; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6() { return cLeftParenthesisKeyword_6; }
		
		//superBox+=[Box]
		public Assignment getSuperBoxAssignment_7() { return cSuperBoxAssignment_7; }
		
		//[Box]
		public CrossReference getSuperBoxBoxCrossReference_7_0() { return cSuperBoxBoxCrossReference_7_0; }
		
		//ID
		public RuleCall getSuperBoxBoxIDTerminalRuleCall_7_0_1() { return cSuperBoxBoxIDTerminalRuleCall_7_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'boxes'
		public Keyword getBoxesKeyword_9() { return cBoxesKeyword_9; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_10() { return cLeftParenthesisKeyword_10; }
		
		//box+=[Box]
		public Assignment getBoxAssignment_11() { return cBoxAssignment_11; }
		
		//[Box]
		public CrossReference getBoxBoxCrossReference_11_0() { return cBoxBoxCrossReference_11_0; }
		
		//ID
		public RuleCall getBoxBoxIDTerminalRuleCall_11_0_1() { return cBoxBoxIDTerminalRuleCall_11_0_1; }
		
		//("," box+=[Box])+
		public Group getGroup_12() { return cGroup_12; }
		
		//","
		public Keyword getCommaKeyword_12_0() { return cCommaKeyword_12_0; }
		
		//box+=[Box]
		public Assignment getBoxAssignment_12_1() { return cBoxAssignment_12_1; }
		
		//[Box]
		public CrossReference getBoxBoxCrossReference_12_1_0() { return cBoxBoxCrossReference_12_1_0; }
		
		//ID
		public RuleCall getBoxBoxIDTerminalRuleCall_12_1_0_1() { return cBoxBoxIDTerminalRuleCall_12_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_13() { return cRightParenthesisKeyword_13; }
		
		//// modification de '*' pour un '+'
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFeatureAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Feature:
		//	{Feature} name=EString?
		//	//'}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Feature} name=EString?
		public Group getGroup() { return cGroup; }
		
		//{Feature}
		public Action getFeatureAction_0() { return cFeatureAction_0; }
		
		////Suppression de tous les aspects syntaxiques de feature afin de simplifier la syntaxe des boites
		////'Feature'
		//// '{'
		//name=EString?
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.ter_metamodel.ecfdl.ECFDL.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false'
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	private final FileElements pFile;
	private final EcfdElements pEcfd;
	private final ElementElements pElement;
	private final MutexElements pMutex;
	private final BoxElements pBox;
	private final GroupBoxElements pGroupBox;
	private final FeatureElements pFeature;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ECFDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pFile = new FileElements();
		this.pEcfd = new EcfdElements();
		this.pElement = new ElementElements();
		this.pMutex = new MutexElements();
		this.pBox = new BoxElements();
		this.pGroupBox = new GroupBoxElements();
		this.pFeature = new FeatureElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.ter_metamodel.ecfdl.ECFDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//File:
	//	'listEcfd' '{' ecfd+=Ecfd ("," ecfd+=Ecfd)* '}';
	public FileElements getFileAccess() {
		return pFile;
	}
	
	public ParserRule getFileRule() {
		return getFileAccess().getRule();
	}
	
	//Ecfd:
	//	{Ecfd}
	//	'Ecfd' ':' name=ID
	//	'{' ('boxes' '{' boxes+=Box ("," boxes+=Box)* '}') ('groups' '{' groups+=GroupBox ("," boxes+=GroupBox)* '}')?
	//	('mutex' '{' (mutex+=Mutex ("," mutex+=Mutex)*)? '}')?
	//	'}';
	public EcfdElements getEcfdAccess() {
		return pEcfd;
	}
	
	public ParserRule getEcfdRule() {
		return getEcfdAccess().getRule();
	}
	
	//Element:
	//	Box | GroupBox;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//Mutex:
	//	'Mutex' ':' name=ID
	//	'{'
	//	'boxes' '(' box+=[Box] ("," box+=[Box])+ ')' // modification de '*' pour un '+'
	//	'}';
	public MutexElements getMutexAccess() {
		return pMutex;
	}
	
	public ParserRule getMutexRule() {
		return getMutexAccess().getRule();
	}
	
	//Box:
	//	{Box}
	//	'Box' ':' name=ID
	//	'{'
	//	Root?='Root'? ('superBox' '(' superBox+=[Box] ("," superBox+=[Box])* ')')? ('groupbox' '(' groupbox+=[GroupBox] (","
	//	groupbox+=[GroupBox])* ')')? ('motherOf' '(' childBox+=[Box] ("," childBox+=[Box])* ')')? ('motherOfGroup' '('
	//	childGroup+=[GroupBox] ("," childGroup+=[GroupBox])* ')')? ('mutex' '(' mutex+=[Mutex] ("," mutex+=[Mutex])* ')')?
	//	('features' '(' feature+=Feature ("," feature+=Feature)* ')')?
	//	'}';
	public BoxElements getBoxAccess() {
		return pBox;
	}
	
	public ParserRule getBoxRule() {
		return getBoxAccess().getRule();
	}
	
	//GroupBox:
	//	'GroupBox' ':' name=ID
	//	'{'
	//	Exclusif?='Exclusif'?
	//	'superBox' '(' superBox+=[Box] ')'
	//	'boxes' '(' box+=[Box] ("," box+=[Box])+ ')' // modification de '*' pour un '+'
	//	'}';
	public GroupBoxElements getGroupBoxAccess() {
		return pGroupBox;
	}
	
	public ParserRule getGroupBoxRule() {
		return getGroupBoxAccess().getRule();
	}
	
	//Feature:
	//	{Feature} name=EString?
	//	//'}'
	//;
	public FeatureElements getFeatureAccess() {
		return pFeature;
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false'
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
