/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ECFDLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/ter_metamodel/ecfdl/parser/antlr/internal/InternalECFDL.tokens");
	}
}
