/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.ecfd;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Box</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#isRoot <em>Root</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getGroupbox <em>Groupbox</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getChildBox <em>Child Box</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getChildGroup <em>Child Group</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getMutex <em>Mutex</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getFeature <em>Feature</em>}</li>
 * </ul>
 *
 * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getBox()
 * @model
 * @generated
 */
public interface Box extends Element
{
  /**
   * Returns the value of the '<em><b>Root</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Root</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Root</em>' attribute.
   * @see #setRoot(boolean)
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getBox_Root()
   * @model
   * @generated
   */
  boolean isRoot();

  /**
   * Sets the value of the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#isRoot <em>Root</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Root</em>' attribute.
   * @see #isRoot()
   * @generated
   */
  void setRoot(boolean value);

  /**
   * Returns the value of the '<em><b>Groupbox</b></em>' reference list.
   * The list contents are of type {@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Groupbox</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Groupbox</em>' reference list.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getBox_Groupbox()
   * @model
   * @generated
   */
  EList<GroupBox> getGroupbox();

  /**
   * Returns the value of the '<em><b>Child Box</b></em>' reference list.
   * The list contents are of type {@link org.xtext.ter_metamodel.ecfdl.ecfd.Box}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Child Box</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child Box</em>' reference list.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getBox_ChildBox()
   * @model
   * @generated
   */
  EList<Box> getChildBox();

  /**
   * Returns the value of the '<em><b>Child Group</b></em>' reference list.
   * The list contents are of type {@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Child Group</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child Group</em>' reference list.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getBox_ChildGroup()
   * @model
   * @generated
   */
  EList<GroupBox> getChildGroup();

  /**
   * Returns the value of the '<em><b>Mutex</b></em>' reference list.
   * The list contents are of type {@link org.xtext.ter_metamodel.ecfdl.ecfd.Mutex}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mutex</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mutex</em>' reference list.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getBox_Mutex()
   * @model
   * @generated
   */
  EList<Mutex> getMutex();

  /**
   * Returns the value of the '<em><b>Feature</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.ter_metamodel.ecfdl.ecfd.Feature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Feature</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feature</em>' containment reference list.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getBox_Feature()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getFeature();

} // Box
