/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.ecfd;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdFactory
 * @model kind="package"
 * @generated
 */
public interface EcfdPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ecfd";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/ter_metamodel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ecfd";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EcfdPackage eINSTANCE = org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.FileImpl <em>File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.FileImpl
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getFile()
   * @generated
   */
  int FILE = 0;

  /**
   * The feature id for the '<em><b>Ecfd</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE__ECFD = 0;

  /**
   * The number of structural features of the '<em>File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl <em>Ecfd</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getEcfd()
   * @generated
   */
  int ECFD = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECFD__NAME = 0;

  /**
   * The feature id for the '<em><b>Boxes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECFD__BOXES = 1;

  /**
   * The feature id for the '<em><b>Groups</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECFD__GROUPS = 2;

  /**
   * The feature id for the '<em><b>Mutex</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECFD__MUTEX = 3;

  /**
   * The number of structural features of the '<em>Ecfd</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ECFD_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.ElementImpl
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Super Box</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__SUPER_BOX = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.MutexImpl <em>Mutex</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.MutexImpl
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getMutex()
   * @generated
   */
  int MUTEX = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUTEX__NAME = 0;

  /**
   * The feature id for the '<em><b>Box</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUTEX__BOX = 1;

  /**
   * The number of structural features of the '<em>Mutex</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUTEX_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.BoxImpl <em>Box</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.BoxImpl
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getBox()
   * @generated
   */
  int BOX = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Super Box</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__SUPER_BOX = ELEMENT__SUPER_BOX;

  /**
   * The feature id for the '<em><b>Root</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__ROOT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Groupbox</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__GROUPBOX = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Child Box</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__CHILD_BOX = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Child Group</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__CHILD_GROUP = ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Mutex</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__MUTEX = ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Feature</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX__FEATURE = ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Box</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOX_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.GroupBoxImpl <em>Group Box</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.GroupBoxImpl
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getGroupBox()
   * @generated
   */
  int GROUP_BOX = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_BOX__NAME = ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Super Box</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_BOX__SUPER_BOX = ELEMENT__SUPER_BOX;

  /**
   * The feature id for the '<em><b>Exclusif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_BOX__EXCLUSIF = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Box</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_BOX__BOX = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Group Box</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_BOX_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.FeatureImpl <em>Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.FeatureImpl
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getFeature()
   * @generated
   */
  int FEATURE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE__NAME = 0;

  /**
   * The number of structural features of the '<em>Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.ter_metamodel.ecfdl.ecfd.File <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.File
   * @generated
   */
  EClass getFile();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.File#getEcfd <em>Ecfd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ecfd</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.File#getEcfd()
   * @see #getFile()
   * @generated
   */
  EReference getFile_Ecfd();

  /**
   * Returns the meta object for class '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd <em>Ecfd</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ecfd</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd
   * @generated
   */
  EClass getEcfd();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getName()
   * @see #getEcfd()
   * @generated
   */
  EAttribute getEcfd_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getBoxes <em>Boxes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Boxes</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getBoxes()
   * @see #getEcfd()
   * @generated
   */
  EReference getEcfd_Boxes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getGroups <em>Groups</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Groups</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getGroups()
   * @see #getEcfd()
   * @generated
   */
  EReference getEcfd_Groups();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getMutex <em>Mutex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mutex</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd#getMutex()
   * @see #getEcfd()
   * @generated
   */
  EReference getEcfd_Mutex();

  /**
   * Returns the meta object for class '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Element#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Element#getName()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Element#getSuperBox <em>Super Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Super Box</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Element#getSuperBox()
   * @see #getElement()
   * @generated
   */
  EReference getElement_SuperBox();

  /**
   * Returns the meta object for class '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Mutex <em>Mutex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mutex</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Mutex
   * @generated
   */
  EClass getMutex();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Mutex#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Mutex#getName()
   * @see #getMutex()
   * @generated
   */
  EAttribute getMutex_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Mutex#getBox <em>Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Box</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Mutex#getBox()
   * @see #getMutex()
   * @generated
   */
  EReference getMutex_Box();

  /**
   * Returns the meta object for class '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box <em>Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Box</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Box
   * @generated
   */
  EClass getBox();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#isRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Root</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Box#isRoot()
   * @see #getBox()
   * @generated
   */
  EAttribute getBox_Root();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getGroupbox <em>Groupbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Groupbox</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Box#getGroupbox()
   * @see #getBox()
   * @generated
   */
  EReference getBox_Groupbox();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getChildBox <em>Child Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Child Box</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Box#getChildBox()
   * @see #getBox()
   * @generated
   */
  EReference getBox_ChildBox();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getChildGroup <em>Child Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Child Group</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Box#getChildGroup()
   * @see #getBox()
   * @generated
   */
  EReference getBox_ChildGroup();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getMutex <em>Mutex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Mutex</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Box#getMutex()
   * @see #getBox()
   * @generated
   */
  EReference getBox_Mutex();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Box#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Feature</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Box#getFeature()
   * @see #getBox()
   * @generated
   */
  EReference getBox_Feature();

  /**
   * Returns the meta object for class '{@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox <em>Group Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group Box</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox
   * @generated
   */
  EClass getGroupBox();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox#isExclusif <em>Exclusif</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exclusif</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox#isExclusif()
   * @see #getGroupBox()
   * @generated
   */
  EAttribute getGroupBox_Exclusif();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox#getBox <em>Box</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Box</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox#getBox()
   * @see #getGroupBox()
   * @generated
   */
  EReference getGroupBox_Box();

  /**
   * Returns the meta object for class '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Feature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Feature
   * @generated
   */
  EClass getFeature();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.ter_metamodel.ecfdl.ecfd.Feature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.Feature#getName()
   * @see #getFeature()
   * @generated
   */
  EAttribute getFeature_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EcfdFactory getEcfdFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.FileImpl <em>File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.FileImpl
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getFile()
     * @generated
     */
    EClass FILE = eINSTANCE.getFile();

    /**
     * The meta object literal for the '<em><b>Ecfd</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILE__ECFD = eINSTANCE.getFile_Ecfd();

    /**
     * The meta object literal for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl <em>Ecfd</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getEcfd()
     * @generated
     */
    EClass ECFD = eINSTANCE.getEcfd();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ECFD__NAME = eINSTANCE.getEcfd_Name();

    /**
     * The meta object literal for the '<em><b>Boxes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ECFD__BOXES = eINSTANCE.getEcfd_Boxes();

    /**
     * The meta object literal for the '<em><b>Groups</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ECFD__GROUPS = eINSTANCE.getEcfd_Groups();

    /**
     * The meta object literal for the '<em><b>Mutex</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ECFD__MUTEX = eINSTANCE.getEcfd_Mutex();

    /**
     * The meta object literal for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.ElementImpl
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__NAME = eINSTANCE.getElement_Name();

    /**
     * The meta object literal for the '<em><b>Super Box</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT__SUPER_BOX = eINSTANCE.getElement_SuperBox();

    /**
     * The meta object literal for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.MutexImpl <em>Mutex</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.MutexImpl
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getMutex()
     * @generated
     */
    EClass MUTEX = eINSTANCE.getMutex();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MUTEX__NAME = eINSTANCE.getMutex_Name();

    /**
     * The meta object literal for the '<em><b>Box</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUTEX__BOX = eINSTANCE.getMutex_Box();

    /**
     * The meta object literal for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.BoxImpl <em>Box</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.BoxImpl
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getBox()
     * @generated
     */
    EClass BOX = eINSTANCE.getBox();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOX__ROOT = eINSTANCE.getBox_Root();

    /**
     * The meta object literal for the '<em><b>Groupbox</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOX__GROUPBOX = eINSTANCE.getBox_Groupbox();

    /**
     * The meta object literal for the '<em><b>Child Box</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOX__CHILD_BOX = eINSTANCE.getBox_ChildBox();

    /**
     * The meta object literal for the '<em><b>Child Group</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOX__CHILD_GROUP = eINSTANCE.getBox_ChildGroup();

    /**
     * The meta object literal for the '<em><b>Mutex</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOX__MUTEX = eINSTANCE.getBox_Mutex();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOX__FEATURE = eINSTANCE.getBox_Feature();

    /**
     * The meta object literal for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.GroupBoxImpl <em>Group Box</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.GroupBoxImpl
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getGroupBox()
     * @generated
     */
    EClass GROUP_BOX = eINSTANCE.getGroupBox();

    /**
     * The meta object literal for the '<em><b>Exclusif</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GROUP_BOX__EXCLUSIF = eINSTANCE.getGroupBox_Exclusif();

    /**
     * The meta object literal for the '<em><b>Box</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_BOX__BOX = eINSTANCE.getGroupBox_Box();

    /**
     * The meta object literal for the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.FeatureImpl <em>Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.FeatureImpl
     * @see org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdPackageImpl#getFeature()
     * @generated
     */
    EClass FEATURE = eINSTANCE.getFeature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE__NAME = eINSTANCE.getFeature_Name();

  }

} //EcfdPackage
