/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.ecfd;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group Box</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox#isExclusif <em>Exclusif</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox#getBox <em>Box</em>}</li>
 * </ul>
 *
 * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getGroupBox()
 * @model
 * @generated
 */
public interface GroupBox extends Element
{
  /**
   * Returns the value of the '<em><b>Exclusif</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exclusif</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclusif</em>' attribute.
   * @see #setExclusif(boolean)
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getGroupBox_Exclusif()
   * @model
   * @generated
   */
  boolean isExclusif();

  /**
   * Sets the value of the '{@link org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox#isExclusif <em>Exclusif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exclusif</em>' attribute.
   * @see #isExclusif()
   * @generated
   */
  void setExclusif(boolean value);

  /**
   * Returns the value of the '<em><b>Box</b></em>' reference list.
   * The list contents are of type {@link org.xtext.ter_metamodel.ecfdl.ecfd.Box}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Box</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Box</em>' reference list.
   * @see org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage#getGroupBox_Box()
   * @model
   * @generated
   */
  EList<Box> getBox();

} // GroupBox
