/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.ter_metamodel.ecfdl.ecfd.File;
import org.xtext.ter_metamodel.ecfdl.tests.ECFDLInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(ECFDLInjectorProvider.class)
@SuppressWarnings("all")
public class ECFDLParsingTest {
  @Inject
  private ParseHelper<File> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final File result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
