/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.ecfd.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.ter_metamodel.ecfdl.ecfd.Ecfd;
import org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage;
import org.xtext.ter_metamodel.ecfdl.ecfd.Element;
import org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox;
import org.xtext.ter_metamodel.ecfdl.ecfd.Mutex;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ecfd</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl#getBoxes <em>Boxes</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl#getGroups <em>Groups</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.EcfdImpl#getMutex <em>Mutex</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EcfdImpl extends MinimalEObjectImpl.Container implements Ecfd
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getBoxes() <em>Boxes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBoxes()
   * @generated
   * @ordered
   */
  protected EList<Element> boxes;

  /**
   * The cached value of the '{@link #getGroups() <em>Groups</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGroups()
   * @generated
   * @ordered
   */
  protected EList<GroupBox> groups;

  /**
   * The cached value of the '{@link #getMutex() <em>Mutex</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMutex()
   * @generated
   * @ordered
   */
  protected EList<Mutex> mutex;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EcfdImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EcfdPackage.Literals.ECFD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EcfdPackage.ECFD__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Element> getBoxes()
  {
    if (boxes == null)
    {
      boxes = new EObjectContainmentEList<Element>(Element.class, this, EcfdPackage.ECFD__BOXES);
    }
    return boxes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<GroupBox> getGroups()
  {
    if (groups == null)
    {
      groups = new EObjectContainmentEList<GroupBox>(GroupBox.class, this, EcfdPackage.ECFD__GROUPS);
    }
    return groups;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Mutex> getMutex()
  {
    if (mutex == null)
    {
      mutex = new EObjectContainmentEList<Mutex>(Mutex.class, this, EcfdPackage.ECFD__MUTEX);
    }
    return mutex;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case EcfdPackage.ECFD__BOXES:
        return ((InternalEList<?>)getBoxes()).basicRemove(otherEnd, msgs);
      case EcfdPackage.ECFD__GROUPS:
        return ((InternalEList<?>)getGroups()).basicRemove(otherEnd, msgs);
      case EcfdPackage.ECFD__MUTEX:
        return ((InternalEList<?>)getMutex()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EcfdPackage.ECFD__NAME:
        return getName();
      case EcfdPackage.ECFD__BOXES:
        return getBoxes();
      case EcfdPackage.ECFD__GROUPS:
        return getGroups();
      case EcfdPackage.ECFD__MUTEX:
        return getMutex();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EcfdPackage.ECFD__NAME:
        setName((String)newValue);
        return;
      case EcfdPackage.ECFD__BOXES:
        getBoxes().clear();
        getBoxes().addAll((Collection<? extends Element>)newValue);
        return;
      case EcfdPackage.ECFD__GROUPS:
        getGroups().clear();
        getGroups().addAll((Collection<? extends GroupBox>)newValue);
        return;
      case EcfdPackage.ECFD__MUTEX:
        getMutex().clear();
        getMutex().addAll((Collection<? extends Mutex>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EcfdPackage.ECFD__NAME:
        setName(NAME_EDEFAULT);
        return;
      case EcfdPackage.ECFD__BOXES:
        getBoxes().clear();
        return;
      case EcfdPackage.ECFD__GROUPS:
        getGroups().clear();
        return;
      case EcfdPackage.ECFD__MUTEX:
        getMutex().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EcfdPackage.ECFD__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case EcfdPackage.ECFD__BOXES:
        return boxes != null && !boxes.isEmpty();
      case EcfdPackage.ECFD__GROUPS:
        return groups != null && !groups.isEmpty();
      case EcfdPackage.ECFD__MUTEX:
        return mutex != null && !mutex.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //EcfdImpl
