/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.ecfd.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

import org.xtext.ter_metamodel.ecfdl.ecfd.Box;
import org.xtext.ter_metamodel.ecfdl.ecfd.EcfdPackage;
import org.xtext.ter_metamodel.ecfdl.ecfd.GroupBox;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Group Box</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.GroupBoxImpl#isExclusif <em>Exclusif</em>}</li>
 *   <li>{@link org.xtext.ter_metamodel.ecfdl.ecfd.impl.GroupBoxImpl#getBox <em>Box</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GroupBoxImpl extends ElementImpl implements GroupBox
{
  /**
   * The default value of the '{@link #isExclusif() <em>Exclusif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isExclusif()
   * @generated
   * @ordered
   */
  protected static final boolean EXCLUSIF_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isExclusif() <em>Exclusif</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isExclusif()
   * @generated
   * @ordered
   */
  protected boolean exclusif = EXCLUSIF_EDEFAULT;

  /**
   * The cached value of the '{@link #getBox() <em>Box</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBox()
   * @generated
   * @ordered
   */
  protected EList<Box> box;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GroupBoxImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EcfdPackage.Literals.GROUP_BOX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isExclusif()
  {
    return exclusif;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExclusif(boolean newExclusif)
  {
    boolean oldExclusif = exclusif;
    exclusif = newExclusif;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, EcfdPackage.GROUP_BOX__EXCLUSIF, oldExclusif, exclusif));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Box> getBox()
  {
    if (box == null)
    {
      box = new EObjectResolvingEList<Box>(Box.class, this, EcfdPackage.GROUP_BOX__BOX);
    }
    return box;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case EcfdPackage.GROUP_BOX__EXCLUSIF:
        return isExclusif();
      case EcfdPackage.GROUP_BOX__BOX:
        return getBox();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case EcfdPackage.GROUP_BOX__EXCLUSIF:
        setExclusif((Boolean)newValue);
        return;
      case EcfdPackage.GROUP_BOX__BOX:
        getBox().clear();
        getBox().addAll((Collection<? extends Box>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case EcfdPackage.GROUP_BOX__EXCLUSIF:
        setExclusif(EXCLUSIF_EDEFAULT);
        return;
      case EcfdPackage.GROUP_BOX__BOX:
        getBox().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case EcfdPackage.GROUP_BOX__EXCLUSIF:
        return exclusif != EXCLUSIF_EDEFAULT;
      case EcfdPackage.GROUP_BOX__BOX:
        return box != null && !box.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (Exclusif: ");
    result.append(exclusif);
    result.append(')');
    return result.toString();
  }

} //GroupBoxImpl
