/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.ter_metamodel.ecfdl.ecfd.File

@RunWith(XtextRunner)
@InjectWith(ECFDLInjectorProvider)
class ECFDLParsingTest{

	@Inject
	ParseHelper<File> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
