/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl;

import org.xtext.ter_metamodel.ecfdl.AbstractECFDLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ECFDLRuntimeModule extends AbstractECFDLRuntimeModule {
}
