/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl;

import org.xtext.ter_metamodel.ecfdl.ECFDLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ECFDLStandaloneSetup extends ECFDLStandaloneSetupGenerated {
  public static void doSetup() {
    ECFDLStandaloneSetup _eCFDLStandaloneSetup = new ECFDLStandaloneSetup();
    _eCFDLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
