/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ECFDLStandaloneSetup extends ECFDLStandaloneSetupGenerated {

	def static void doSetup() {
		new ECFDLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
