/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractECFDLScopeProvider extends DelegatingScopeProvider {
}
