/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.scoping;

import org.xtext.ter_metamodel.ecfdl.scoping.AbstractECFDLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ECFDLScopeProvider extends AbstractECFDLScopeProvider {
}
