/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.validation;

import org.xtext.ter_metamodel.ecfdl.validation.AbstractECFDLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ECFDLValidator extends AbstractECFDLValidator {
}
