/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ter_metamodel.ecfdl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.ter_metamodel.ecfdl.ui.internal.EcfdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ECFDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EcfdlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EcfdlActivator.getInstance().getInjector(EcfdlActivator.ORG_XTEXT_TER_METAMODEL_ECFDL_ECFDL);
	}
	
}
